name: Test app

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependsncies
        run: npm ci
      - name: install test dependancy
        run: npm install -g test@3.3.0
      - name: Test application
        run: npm test